name: Build and Test
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node environment
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependency and build
        run: |
          npm ci
          npm run build
          npm run test
